### PR TITLE
Allow user to set jenkinsSvcAccount value

### PR DESCRIPTION
**Pull request by jameerpathan111**
We are using this library in SatelliteQE and in OCP the SvC account is different than what's set here and hence we want to make it configurable.

### CODE REVIEW

**Review by Victoremepunto — CHANGES_REQUESTED** [review]
Please can you provide a description to the PR and some context on why is this needed ? a JIRA issue link is okay too.

**Comment by jameerpathan111** [comment]
> Please can you provide a description to the PR and some context on why is this needed ? a JIRA issue link is okay too.

@Victoremepunto we are using this lib in SatelliteQE and in OCP the SvC account is different than what's set here and hence we need it configurable.

**Comment by jyejare** [comment]
@Victoremepunto Hey!

As part of RHC E2E testing, Insights and Sat QE team worked on planning and implementation of integrating Satellite's Robottelo framework and IQEs iqe-remediation framework to run the both frameworks test cases collectively on some teams CI. 

Currently SatQE CI is running these framework integrated tests. The SatQE CI is deployed on OCP with different parameters that IQR and the SvC account is different. Everything else is easily parameterized for creating node on OCP but only SvC account is not parameterized.

So this PR would help us to do that ! We are blocked on this implementation !!

**Review by bsquizz — APPROVED** [review]
Should be OK since the previously configured value is set as a default.

**Review by Victoremepunto — APPROVED** [review]

**Comment by Victoremepunto** [comment]
> Should be OK since the previously configured value is set as a default.

Thanks @bsquizz for reviewing too

**Comment by jameerpathan111** [comment]
Thanks all!

**Pull request merged**
