### PR TITLE
Update clientUtils to support the new iqe-rhc-client-plugin

### PR DESCRIPTION
**Pull request by rodrigonull**

### CODE REVIEW

**Review by bsquizz — CHANGES_REQUESTED** [review]
I think you're duplicating logic already written here:

https://github.com/RedHatInsights/insights-pipeline-lib/blob/master/vars/iqeUtils.groovy#L432-L463

Maybe I am missing a detail that makes that code not usable by you. Do you see an opportunity to re-use that logic?

**Comment by quarckster** [comment]
I'm just wondering why `clientUtils` is still maintained, it should be rewritten on python and included in a plugin.

**Comment by rodrigonull** [comment]
> I think you're duplicating logic already written here:
> 
> https://github.com/RedHatInsights/insights-pipeline-lib/blob/master/vars/iqeUtils.groovy#L432-L463
> 
> Maybe I am missing a detail that makes that code not usable by you. Do you see an opportunity to re-use that logic?

@bsquizz I updated the code to reuse the `writeVaultEnvVars` function. I'm not sure the way I did it is the best way, but let me know if you have any other suggestions.

**Comment by rodrigonull** [comment]
> I'm just wondering why `clientUtils` is still maintained, it should be rewritten on python and included in a plugin.

This is a good point. I think it would be a lot of work due migrating all this code to a plugin, but it would be easier to maintain.

What do you think @patchkez?

**Comment by rodrigonull** [comment]
@patchkez I tried this code in a test pipeline and everything is working as expected.

**Comment by quarckster** [comment]
> but it would be easier to maintain.
no doubt it will, at least you can add some unit tests, run the script locally, and so on.

**Review by bsquizz — APPROVED** [review]
My concern was addressed, so I'll approve :) @quarckster do you want this to be reworked further or have that done in a follow-up?

**Comment by quarckster** [comment]
> @quarckster do you want this to be reworked further or have that done in a follow-up?

My concern is definitely out of the scope of this PR. I would like to see at least jira cards with a plan to rework `clientUtils`

**Comment by patchkez** [comment]
> > I'm just wondering why `clientUtils` is still maintained, it should be rewritten on python and included in a plugin.
> 
> This is a good point. I think it would be a lot of work due migrating all this code to a plugin, but it would be easier to maintain.
> 
> What do you think @patchkez?

Yes, that is the plan to remove groovy code from clientUtils and put it into script or ansible playbook. I will open card to work on it.

**Pull request merged**
